/****************************************************************************
 * Digital Circuit Synthesis Final Project
 * Controller, Datapath, and Testbench generation using Data Flow Graphs
 * 
 * Authors: Anthony Teresi, Mary Mouro, and Andy Rivero
 * 
 * Header File
 * Generates the VHDL file using the data structures generated by the controller class
****************************************************************************/

#ifndef CONTROLLER_VHDL_H
#define CONTROLLER_VHDL_H

#include <fstream>
#include <string>
#include <algorithm>
#include "controller.h"
#include "datapath.h"

using std::ostream;
using std::string;

class controller_vhdl
{
private:
	controller &contr;
	datapath &dp;
	string entity_name;
	
	void create_entity (ostream &);	
	void create_architecture (ostream &);
	void create_signals (ostream &);
	void create_process (ostream &);
	void max_timestep ();

public:

	// constructor
	controller_vhdl (controller &contr, datapath &dp, string entity_name) 
		: contr (contr), dp (dp), entity_name(entity_name) {}

	// public interface
	void create_vhdl_code (ostream &);
};

#endif